parameters:
- name: buildPostfix 
  type: string
  default: ''
- name: PAT 
  type: string
- name: AdditionalCommandArgs 
  type: string
  default: ''
- name: Version 
  type: string
- name: BaseUri 
  type: string
  default: ''


steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Use Node.js@12.x'

- script: npm install -g npm@8
  displayName: 'Use NPM@8.x'

- script: npm ci
  displayName: 'Install dependencies'

- script: npm run build${{ parameters.buildPostfix }}
  displayName: 'Run build'

- script: |
    npm run publish-extension${{ parameters.buildPostfix }} -- -t "${{ parameters.PAT }}" --override '{"version":"${{ parameters.Version }}","baseUri":"${{ parameters.BaseUri }}"}' ${{ parameters.AdditionalCommandArgs }}
  displayName: 'publish build'

  
    
