parameters:
- name: buildPostfix 
  type: string
  default: ''
- name: additionalCommandArgs 
  type: string
  default: ''
- name: baseUri 
  type: string
  default: ''
- name: setGitTag 
  type: boolean
  default: false

steps:
- checkout: self
  persistCredentials: true

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Use Node.js@16.x'

- script: npm install -g npm@8.7
  displayName: 'Use NPM@8.7.x'

- script: npm ci
  displayName: 'Install dependencies'

- script: npm run build${{ parameters.buildPostfix }}
  displayName: 'Run build'

- script: |
    npm run publish-extension${{ parameters.buildPostfix }} -- -t "$(PUBLISH_TOKEN)" --override '{"version":"$(version)","baseUri":"${{ parameters.baseUri }}"}' ${{ parameters.additionalCommandArgs }}
  displayName: 'Publish extension'
  condition: eq(variables.isDependabot, 'false')

- script: |
     git tag $(version)
     git push origin $(version)
  workingDirectory: $(Build.SourcesDirectory)
  condition: eq('${{ parameters.setGitTag }}', 'true')
